CREATE TABLE t_orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_price BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    voucher_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    INDEX (id),
    PRIMARY KEY (id)
);

ALTER TABLE t_orders
ADD CONSTRAINT FK_Vouchers_Orders FOREIGN KEY (voucher_id) REFERENCES m_vouchers(id),
ADD CONSTRAINT FK_Users_Orders FOREIGN KEY (user_id) REFERENCES m_users(id);