CREATE TABLE t_orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_price INT NOT NULL DEFAULT 0,
    voucher_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    INDEX (id),
    PRIMARY KEY (id)
);

ALTER TABLE t_orders
ADD CONSTRAINT FK1 FOREIGN KEY (voucher_id) REFERENCES m_vouchers(id);